CREATE TABLE "AppSettings" (
    "Key" character varying(120) NOT NULL,
    "Value" character varying(2048),
    "UpdatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_AppSettings" PRIMARY KEY ("Key")
);


CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);


CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);


CREATE TABLE "ClientGroups" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(120) NOT NULL,
    "OutletGroupNames" character varying(1000) NOT NULL,
    "IsActive" boolean NOT NULL,
    "DisplayOrder" integer NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_ClientGroups" PRIMARY KEY ("Id")
);


CREATE TABLE "CollectionReceivedOverrides" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StartDate" timestamp without time zone NOT NULL,
    "EndDate" timestamp without time zone NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_CollectionReceivedOverrides" PRIMARY KEY ("Id")
);


CREATE TABLE "Customers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Address" character varying(200),
    "ContactPerson" character varying(50),
    "ContactNumber" character varying(50),
    "IsActive" boolean NOT NULL,
    "GroupName" character varying(100) NOT NULL,
    "SubLabel" character varying(50),
    CONSTRAINT "PK_Customers" PRIMARY KEY ("Id")
);


CREATE TABLE "Deductions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Date" timestamp without time zone NOT NULL,
    "Description" character varying(200) NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Category" character varying(50),
    "AppliedTo" character varying(50),
    CONSTRAINT "PK_Deductions" PRIMARY KEY ("Id")
);


CREATE TABLE "ExpenseCategoryDefinitions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "Group" integer NOT NULL,
    "IsSystem" boolean NOT NULL,
    CONSTRAINT "PK_ExpenseCategoryDefinitions" PRIMARY KEY ("Id")
);


CREATE TABLE "Expenses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Date" timestamp without time zone NOT NULL,
    "Category" character varying(50) NOT NULL,
    "Vendor" character varying(100),
    "Amount" numeric(18,2) NOT NULL,
    "PaymentMethod" integer NOT NULL,
    "ReferenceNo" character varying(50),
    "Description" character varying(200),
    "RecordedById" text,
    CONSTRAINT "PK_Expenses" PRIMARY KEY ("Id")
);


CREATE TABLE "Goals" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Month" integer NOT NULL,
    "Year" integer NOT NULL,
    "SalesTarget" numeric(18,2) NOT NULL,
    "NetProfitTarget" numeric(18,2) NOT NULL,
    "ExpenseBudget" numeric(18,2) NOT NULL,
    CONSTRAINT "PK_Goals" PRIMARY KEY ("Id")
);


CREATE TABLE "Laborers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(20),
    "FullName" character varying(120) NOT NULL,
    "DailyRate" numeric(18,2) NOT NULL,
    "Role" character varying(80),
    "ContactNumber" character varying(50),
    "Address" character varying(200),
    "HiredDate" timestamp without time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "ArchivedAt" timestamp without time zone,
    "Notes" character varying(200),
    CONSTRAINT "PK_Laborers" PRIMARY KEY ("Id")
);


CREATE TABLE "PartnerBalanceConfigs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PartnerName" character varying(50) NOT NULL,
    "OpeningBalance" numeric(18,2) NOT NULL,
    "AsOfDate" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_PartnerBalanceConfigs" PRIMARY KEY ("Id")
);


CREATE TABLE "PartnerCapitals" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Date" timestamp without time zone NOT NULL,
    "FundName" character varying(120),
    "Amount" numeric(18,2) NOT NULL,
    "Description" character varying(100) NOT NULL,
    CONSTRAINT "PK_PartnerCapitals" PRIMARY KEY ("Id")
);


CREATE TABLE "PartnerPurchases" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PartnerName" character varying(50) NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Notes" character varying(200),
    CONSTRAINT "PK_PartnerPurchases" PRIMARY KEY ("Id")
);


CREATE TABLE "PayrollCutoffs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StartDate" timestamp without time zone NOT NULL,
    "EndDate" timestamp without time zone NOT NULL,
    "IsLocked" boolean NOT NULL,
    "LockedAt" timestamp without time zone,
    "LockedBy" character varying(100),
    "Notes" character varying(200),
    CONSTRAINT "PK_PayrollCutoffs" PRIMARY KEY ("Id")
);


CREATE TABLE "PayrollRuns" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WeekStart" timestamp without time zone NOT NULL,
    "WeekEnd" timestamp without time zone NOT NULL,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "ApprovedAt" timestamp without time zone,
    "ClosedAt" timestamp without time zone,
    "CreatedBy" character varying(100),
    "Notes" character varying(200),
    CONSTRAINT "PK_PayrollRuns" PRIMARY KEY ("Id")
);


CREATE TABLE "PurchaseSequences" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Year" integer NOT NULL,
    "LastNumber" integer NOT NULL,
    CONSTRAINT "PK_PurchaseSequences" PRIMARY KEY ("Id")
);


CREATE TABLE "ReceiptSequences" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Year" integer NOT NULL,
    "LastNumber" integer NOT NULL,
    CONSTRAINT "PK_ReceiptSequences" PRIMARY KEY ("Id")
);


CREATE TABLE "Services" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Rate" numeric(18,2) NOT NULL,
    "Cost" numeric(18,2),
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Services" PRIMARY KEY ("Id")
);


CREATE TABLE "Suppliers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(120) NOT NULL,
    "ContactPerson" character varying(100),
    "ContactNumber" character varying(50),
    "Address" character varying(200),
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Suppliers" PRIMARY KEY ("Id")
);


CREATE TABLE "Supplies" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Unit" character varying(20) NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Supplies" PRIMARY KEY ("Id")
);


CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" character varying(128) NOT NULL,
    "ProviderKey" character varying(128) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" character varying(128) NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Receipts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReceiptNumber" character varying(20) NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    "CustomerId" integer,
    "CustomerName" character varying(100) NOT NULL,
    "CustomerAddress" character varying(200),
    "ContactNumber" character varying(50),
    "TotalAmount" numeric(18,2) NOT NULL,
    "PaidAmount" numeric(18,2) NOT NULL,
    "Type" integer NOT NULL,
    "Status" integer NOT NULL,
    "CreatedById" text,
    "ReceivedBy" character varying(100),
    CONSTRAINT "PK_Receipts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Receipts_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE SET NULL
);


CREATE TABLE "CashAdvances" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "LaborerId" integer NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "RemainingBalance" numeric(18,2) NOT NULL,
    "Notes" character varying(200),
    "RecordedById" text,
    CONSTRAINT "PK_CashAdvances" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CashAdvances_Laborers_LaborerId" FOREIGN KEY ("LaborerId") REFERENCES "Laborers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "LaborerSchedules" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "LaborerId" integer NOT NULL,
    "WorkDays" character varying(100) NOT NULL,
    "EffectiveDate" timestamp without time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_LaborerSchedules" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LaborerSchedules_Laborers_LaborerId" FOREIGN KEY ("LaborerId") REFERENCES "Laborers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "PayrollEntries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PayrollRunId" integer NOT NULL,
    "LaborerId" integer NOT NULL,
    "PeriodStart" timestamp without time zone NOT NULL,
    "PeriodEnd" timestamp without time zone NOT NULL,
    "TotalDays" integer NOT NULL,
    "GrossWage" numeric(18,2) NOT NULL,
    "TotalDeductions" numeric(18,2) NOT NULL,
    "TotalAdditions" numeric(18,2) NOT NULL,
    "NetPay" numeric(18,2) NOT NULL,
    "PaidAmount" numeric(18,2) NOT NULL,
    "RecordType" integer NOT NULL,
    "Status" integer NOT NULL,
    "GeneratedAt" timestamp without time zone NOT NULL,
    "Notes" character varying(200),
    CONSTRAINT "PK_PayrollEntries" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PayrollEntries_Laborers_LaborerId" FOREIGN KEY ("LaborerId") REFERENCES "Laborers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PayrollEntries_PayrollRuns_PayrollRunId" FOREIGN KEY ("PayrollRunId") REFERENCES "PayrollRuns" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Products" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SKU" character varying(50) NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Category" character varying(50) NOT NULL,
    "OwnerName" character varying(80),
    "SupplierId" integer,
    "Unit" character varying(20) NOT NULL,
    "UnitCost" numeric(18,2) NOT NULL,
    "Markup" numeric(18,2) NOT NULL,
    "DeliveryFee" numeric(18,2) NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Products_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Suppliers" ("Id")
);


CREATE TABLE "Purchases" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PurchaseNumber" character varying(20) NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    "SupplierId" integer,
    "SupplierName" character varying(120) NOT NULL,
    "SupplierAddress" character varying(200),
    "ContactNumber" character varying(50),
    "TotalAmount" numeric(18,2) NOT NULL,
    "PaidAmount" numeric(18,2) NOT NULL,
    "Status" integer NOT NULL,
    "Notes" character varying(200),
    "CreatedById" text,
    CONSTRAINT "PK_Purchases" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Purchases_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Suppliers" ("Id") ON DELETE SET NULL
);


CREATE TABLE "SupplyStockMovements" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SupplyId" integer NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    "Quantity" numeric(18,3) NOT NULL,
    "Type" character varying(50) NOT NULL,
    "Reference" character varying(100),
    "RecordedById" text,
    CONSTRAINT "PK_SupplyStockMovements" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SupplyStockMovements_Supplies_SupplyId" FOREIGN KEY ("SupplyId") REFERENCES "Supplies" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Payments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReceiptId" integer NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Method" integer NOT NULL,
    "ReferenceNo" character varying(50),
    "RecordedById" text,
    CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Payments_Receipts_ReceiptId" FOREIGN KEY ("ReceiptId") REFERENCES "Receipts" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Adjustments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PayrollEntryId" integer NOT NULL,
    "Type" integer NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Reason" character varying(200),
    "Date" timestamp without time zone NOT NULL,
    "CreatedBy" text,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Adjustments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Adjustments_PayrollEntries_PayrollEntryId" FOREIGN KEY ("PayrollEntryId") REFERENCES "PayrollEntries" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AdvanceDeductions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PayrollEntryId" integer NOT NULL,
    "CashAdvanceId" integer NOT NULL,
    "DeductAmount" numeric(18,2) NOT NULL,
    CONSTRAINT "PK_AdvanceDeductions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AdvanceDeductions_CashAdvances_CashAdvanceId" FOREIGN KEY ("CashAdvanceId") REFERENCES "CashAdvances" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AdvanceDeductions_PayrollEntries_PayrollEntryId" FOREIGN KEY ("PayrollEntryId") REFERENCES "PayrollEntries" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AttendanceRecords" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "LaborerId" integer NOT NULL,
    "WorkDate" timestamp without time zone NOT NULL,
    "Status" integer NOT NULL,
    "Source" integer NOT NULL,
    "RateSnapshot" numeric(18,2) NOT NULL,
    "WageAmount" numeric(18,2) NOT NULL,
    "PayrollEntryId" integer,
    "Notes" character varying(200),
    "RecordedById" text,
    CONSTRAINT "PK_AttendanceRecords" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AttendanceRecords_Laborers_LaborerId" FOREIGN KEY ("LaborerId") REFERENCES "Laborers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AttendanceRecords_PayrollEntries_PayrollEntryId" FOREIGN KEY ("PayrollEntryId") REFERENCES "PayrollEntries" ("Id")
);


CREATE TABLE "PayrollPayments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PayrollEntryId" integer NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "PaymentMethod" integer NOT NULL,
    "ReferenceNo" character varying(50),
    "RecordedById" text,
    CONSTRAINT "PK_PayrollPayments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PayrollPayments_PayrollEntries_PayrollEntryId" FOREIGN KEY ("PayrollEntryId") REFERENCES "PayrollEntries" ("Id") ON DELETE CASCADE
);


CREATE TABLE "DailyPurchaseCosts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" integer NOT NULL,
    "CostDate" timestamp without time zone NOT NULL,
    "UnitCost" numeric(18,2) NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone NOT NULL,
    "RecordedById" character varying(120),
    CONSTRAINT "PK_DailyPurchaseCosts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DailyPurchaseCosts_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);


CREATE TABLE "ProductStockMovements" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" integer NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    "Quantity" numeric(18,3) NOT NULL,
    "Type" character varying(50) NOT NULL,
    "Reference" character varying(100),
    "RecordedById" text,
    CONSTRAINT "PK_ProductStockMovements" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProductStockMovements_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);


CREATE TABLE "ReceiptLines" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReceiptId" integer NOT NULL,
    "ProductId" integer,
    "ServiceId" integer,
    "ItemName" character varying(100) NOT NULL,
    "Quantity" numeric(18,3) NOT NULL,
    "Unit" character varying(20) NOT NULL,
    "PartnerName" character varying(50),
    "Price" numeric(18,2) NOT NULL,
    "CostPriceSnapshot" numeric(18,2) NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    CONSTRAINT "PK_ReceiptLines" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ReceiptLines_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id"),
    CONSTRAINT "FK_ReceiptLines_Receipts_ReceiptId" FOREIGN KEY ("ReceiptId") REFERENCES "Receipts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ReceiptLines_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id")
);


CREATE TABLE "WeeklyPrices" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" integer NOT NULL,
    "EffectiveFrom" timestamp without time zone NOT NULL,
    "EffectiveTo" timestamp without time zone NOT NULL,
    "CostOverride" numeric(18,2),
    "BasePrice" numeric(18,2) NOT NULL,
    "DeliveryPrice" numeric(18,2) NOT NULL,
    "Markup" numeric(18,2) NOT NULL,
    "DeliveryFee" numeric(18,2),
    CONSTRAINT "PK_WeeklyPrices" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WeeklyPrices_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);


CREATE TABLE "PurchaseLines" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PurchaseId" integer NOT NULL,
    "ProductId" integer,
    "ItemName" character varying(120) NOT NULL,
    "Quantity" numeric(18,3) NOT NULL,
    "Unit" character varying(20) NOT NULL,
    "Cost" numeric(18,2) NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    CONSTRAINT "PK_PurchaseLines" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PurchaseLines_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id"),
    CONSTRAINT "FK_PurchaseLines_Purchases_PurchaseId" FOREIGN KEY ("PurchaseId") REFERENCES "Purchases" ("Id") ON DELETE CASCADE
);


CREATE TABLE "PurchasePayments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PurchaseId" integer NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "PaymentMethod" integer NOT NULL,
    "ReferenceNo" character varying(50),
    "RecordedById" text,
    CONSTRAINT "PK_PurchasePayments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PurchasePayments_Purchases_PurchaseId" FOREIGN KEY ("PurchaseId") REFERENCES "Purchases" ("Id") ON DELETE CASCADE
);


CREATE INDEX "IX_Adjustments_Date" ON "Adjustments" ("Date");


CREATE INDEX "IX_Adjustments_PayrollEntryId" ON "Adjustments" ("PayrollEntryId");


CREATE INDEX "IX_AdvanceDeductions_CashAdvanceId" ON "AdvanceDeductions" ("CashAdvanceId");


CREATE INDEX "IX_AdvanceDeductions_PayrollEntryId" ON "AdvanceDeductions" ("PayrollEntryId");


CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");


CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");


CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");


CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");


CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");


CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");


CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");


CREATE UNIQUE INDEX "IX_AttendanceRecords_LaborerId_WorkDate" ON "AttendanceRecords" ("LaborerId", "WorkDate");


CREATE INDEX "IX_AttendanceRecords_PayrollEntryId" ON "AttendanceRecords" ("PayrollEntryId");


CREATE INDEX "IX_AttendanceRecords_WorkDate" ON "AttendanceRecords" ("WorkDate");


CREATE INDEX "IX_CashAdvances_LaborerId" ON "CashAdvances" ("LaborerId");


CREATE INDEX "IX_ClientGroups_IsActive" ON "ClientGroups" ("IsActive");


CREATE UNIQUE INDEX "IX_ClientGroups_Name" ON "ClientGroups" ("Name");


CREATE INDEX "IX_Customers_GroupName" ON "Customers" ("GroupName");


CREATE INDEX "IX_Customers_IsActive" ON "Customers" ("IsActive");


CREATE INDEX "IX_Customers_Name" ON "Customers" ("Name");


CREATE INDEX "IX_DailyPurchaseCosts_CostDate" ON "DailyPurchaseCosts" ("CostDate");


CREATE UNIQUE INDEX "IX_DailyPurchaseCosts_ProductId_CostDate" ON "DailyPurchaseCosts" ("ProductId", "CostDate");


CREATE UNIQUE INDEX "IX_ExpenseCategoryDefinitions_Name" ON "ExpenseCategoryDefinitions" ("Name");


CREATE INDEX "IX_LaborerSchedules_LaborerId" ON "LaborerSchedules" ("LaborerId");


CREATE INDEX "IX_Payments_ReceiptId" ON "Payments" ("ReceiptId");


CREATE INDEX "IX_PayrollCutoffs_IsLocked" ON "PayrollCutoffs" ("IsLocked");


CREATE INDEX "IX_PayrollCutoffs_StartDate_EndDate" ON "PayrollCutoffs" ("StartDate", "EndDate");


CREATE INDEX "IX_PayrollEntries_LaborerId" ON "PayrollEntries" ("LaborerId");


CREATE INDEX "IX_PayrollEntries_PayrollRunId" ON "PayrollEntries" ("PayrollRunId");


CREATE INDEX "IX_PayrollEntries_PeriodStart" ON "PayrollEntries" ("PeriodStart");


CREATE INDEX "IX_PayrollEntries_RecordType" ON "PayrollEntries" ("RecordType");


CREATE INDEX "IX_PayrollEntries_Status" ON "PayrollEntries" ("Status");


CREATE INDEX "IX_PayrollPayments_PayrollEntryId" ON "PayrollPayments" ("PayrollEntryId");


CREATE INDEX "IX_PayrollRuns_Status" ON "PayrollRuns" ("Status");


CREATE INDEX "IX_PayrollRuns_WeekStart_WeekEnd" ON "PayrollRuns" ("WeekStart", "WeekEnd");


CREATE INDEX "IX_Products_IsActive" ON "Products" ("IsActive");


CREATE INDEX "IX_Products_SupplierId" ON "Products" ("SupplierId");


CREATE INDEX "IX_ProductStockMovements_ProductId" ON "ProductStockMovements" ("ProductId");


CREATE INDEX "IX_PurchaseLines_ProductId" ON "PurchaseLines" ("ProductId");


CREATE INDEX "IX_PurchaseLines_PurchaseId" ON "PurchaseLines" ("PurchaseId");


CREATE INDEX "IX_PurchasePayments_PurchaseId" ON "PurchasePayments" ("PurchaseId");


CREATE INDEX "IX_Purchases_Date" ON "Purchases" ("Date");


CREATE INDEX "IX_Purchases_PurchaseNumber" ON "Purchases" ("PurchaseNumber");


CREATE INDEX "IX_Purchases_Status" ON "Purchases" ("Status");


CREATE INDEX "IX_Purchases_SupplierId" ON "Purchases" ("SupplierId");


CREATE INDEX "IX_Purchases_SupplierName" ON "Purchases" ("SupplierName");


CREATE INDEX "IX_PurchaseSequences_Year" ON "PurchaseSequences" ("Year");


CREATE INDEX "IX_ReceiptLines_ProductId" ON "ReceiptLines" ("ProductId");


CREATE INDEX "IX_ReceiptLines_ReceiptId" ON "ReceiptLines" ("ReceiptId");


CREATE INDEX "IX_ReceiptLines_ServiceId" ON "ReceiptLines" ("ServiceId");


CREATE INDEX "IX_Receipts_CustomerId" ON "Receipts" ("CustomerId");


CREATE INDEX "IX_Receipts_CustomerId_Date" ON "Receipts" ("CustomerId", "Date");


CREATE INDEX "IX_Receipts_CustomerName" ON "Receipts" ("CustomerName");


CREATE INDEX "IX_Receipts_Date" ON "Receipts" ("Date");


CREATE INDEX "IX_Receipts_Date_Id" ON "Receipts" ("Date", "Id");


CREATE INDEX "IX_Receipts_PaidAmount" ON "Receipts" ("PaidAmount");


CREATE INDEX "IX_Receipts_ReceiptNumber" ON "Receipts" ("ReceiptNumber");


CREATE INDEX "IX_Receipts_Status" ON "Receipts" ("Status");


CREATE INDEX "IX_ReceiptSequences_Year" ON "ReceiptSequences" ("Year");


CREATE INDEX "IX_Suppliers_IsActive" ON "Suppliers" ("IsActive");


CREATE INDEX "IX_SupplyStockMovements_SupplyId" ON "SupplyStockMovements" ("SupplyId");


CREATE INDEX "IX_WeeklyPrices_ProductId_EffectiveFrom_EffectiveTo" ON "WeeklyPrices" ("ProductId", "EffectiveFrom", "EffectiveTo");


