using HazelInvoice.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HazelInvoice.Migrations
{
    /// <inheritdoc />
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260708061000_EnsureDailyPurchaseCostsTable")]
    public partial class EnsureDailyPurchaseCostsTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "DailyPurchaseCosts" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "ProductId" integer NOT NULL,
                    "CostDate" timestamp without time zone NOT NULL,
                    "UnitCost" decimal(18,2) NOT NULL,
                    "CreatedAt" timestamp without time zone NOT NULL,
                    "UpdatedAt" timestamp without time zone NOT NULL,
                    "RecordedById" character varying(120) NULL,
                    CONSTRAINT "PK_DailyPurchaseCosts" PRIMARY KEY ("Id")
                );
                """);

            migrationBuilder.Sql("""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conname = 'FK_DailyPurchaseCosts_Products_ProductId'
                    ) THEN
                        ALTER TABLE "DailyPurchaseCosts"
                        ADD CONSTRAINT "FK_DailyPurchaseCosts_Products_ProductId"
                        FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id")
                        ON DELETE CASCADE;
                    END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_DailyPurchaseCosts_CostDate"
                ON "DailyPurchaseCosts" ("CostDate");
                """);

            migrationBuilder.Sql("""
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_DailyPurchaseCosts_ProductId_CostDate"
                ON "DailyPurchaseCosts" ("ProductId", "CostDate");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Keep this recovery migration non-destructive. Dropping the table on rollback
            // could remove production cost records that were entered after deployment.
        }
    }
}
